### ISSUE TITLE
Unable to pass the parameters with Invoke-Pester

### ISSUE THREAD

**Issue by subhendu-de** [pester/Pester#1713]
## 1. General summary of the issue

I've developed a basic integration test in pester. However I can't pass the parameters while running the test using Invoke-Pester

## 2. Describe Your Environment

Linux - Ubuntu Distro
PowerShell 7
Pester 5

The powershell code is

```
[CmdletBinding()]
param (
  [Parameter()][string]$resourceGroupName,
  [Parameter()][string]$resourceLocation
)

describe ‘check resource group’ {
  $ResourceGroup = Get-AzResourceGroup -Name $resourceGroupName

  it ‘matching the resource name’ {       
    $ResourceGroup.Name | Should -BeExactly $resourceGroupName
  }

  it ‘matching the resource location’ {       
    $ResourceGroup.Location | Should -BeExactly $resourceLocation
  }
}
```

The way I am calling it is

```
Invoke-Pester -Script @{ Path = '.\resource-group.Tests.ps1'; Parameters = @{resourceGroupName = 'sample-rg'; resourceLocation = 'centralus'}}
```

-->

## 3. Expected Behavior

The tests should execute successfully

## 4.Current Behavior

```
System.Management.Automation.ParameterBindingValidationException: Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
 ---> System.Management.Automation.ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at System.Management.Automation.ValidateNotNullOrEmptyAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.CommandProcessorBase.Complete()
at <ScriptBlock>, 
System.Management.Automation.RuntimeException: No test files were found and no scriptblocks were provided.
at Invoke-Pester<End>
```

**Comment by fflaten** [comment]
Parameterized test files are not yet supported in Pester v5. See [Breaking Changes in README](https://github.com/pester/Pester#actual-breaking-changes)

> -Script option was renamed to -Path and takes paths only, it does not take hashtables. Parametrized scripts are not implemented at the moment, which should be solved in 5.1
