### ISSUE TITLE
Should -Invoke creates Sessionstate Error

### ISSUE THREAD

**Issue by JustinGrote** [pester/Pester#1903]
## General summary of the issue
![Capture](https://user-images.githubusercontent.com/15258962/114201708-5b46f900-990b-11eb-90e2-4594661283e4.gif)

## Describe your environment

Pester version     : 5.1.1 C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
PowerShell version : 7.2.0-preview.4
OS version         : Microsoft Windows NT 10.0.19043.0

## Steps to reproduce

```powershell

    It 'Should run <Action> for <MockFile> and remove <RemoveCount> releases' -Tag 'Test' {
        $SCRIPT:MockFileName = $MockFile
        Mock -ModuleName Press Remove-GithubRelease {}
        Mock -ModuleName Press Get-GithubRelease {
            JsonMock Get-GithubRelease/$MockFileName.json
        }
        Mock -ModuleName Press -CommandName $Action -Verifiable -MockWith {
            $SCRIPT:SetReleaseIdResult = $release
        }

        Update-GithubRelease @UpdateGithubReleaseCommonParams

        if ($Action -eq 'Set-GithubRelease') {
            $SCRIPT:SetReleaseIdResult | Should -Be $SetReleaseId
        }
        
        Should -InvokeVerifiable
        Should -Invoke 'Remove-GithubRelease' -Exactly -Times $RemoveCount
    } -TestCases @(
        @{
            MockFile    = 'Null'
            Action      = 'New-GithubRelease'
            RemoveCount = 0
        }
        @{
            MockFile     = 'ExistingDraft'
            Action       = 'Set-GitHubRelease'
            RemoveCount  = 0
            SetReleaseId = 41097540
        }
        @{
            MockFile     = 'ExistingPublished'
            Action       = 'Set-GitHubRelease'
            RemoveCount  = 0
            SetReleaseId = 51097999
        }
        @{
            MockFile    = 'EarlierMinorVersionDraft'
            Action      = 'New-GitHubRelease'
            RemoveCount = 1
        }
        @{
            MockFile    = 'EarlierMajorVersionDraft'
            Action      = 'New-GitHubRelease'
            RemoveCount = 0
        }
        @{
            MockFile     = 'SameVersionPublishedAndDraft'
            Action       = 'Set-GitHubRelease'
            RemoveCount  = 1
            SetReleaseId = 51097999
        }
        @{
            MockFile     = 'MultiplePastDrafts'
            Action       = 'Set-GitHubRelease'
            RemoveCount  = 3 #Should not remove other major versions
            SetReleaseId = 51097999 #Should select later dated one
        }
    )
}
```

## Expected Behavior
Test Would Pass

## Current Behavior
See exception below

### Exception
```
Exception             : 
    Type              : System.Management.Automation.ParameterBindingValidationException
    Message           : Cannot bind argument to parameter 'SessionState' because it is null.
    ParameterName     : SessionState
    ParameterType     : System.Management.Automation.SessionState
    ErrorId           : ParameterArgumentValidationErrorNullNotAllowed
    Line              : 9565
    Offset            : 34
    CommandInvocation : 
        MyCommand        : Test-ParameterFilter
        BoundParameters  : 
            Comparer : System.OrdinalIgnoreCaseComparer
            Count    : 3
            Keys     : 
                Length : 15

                Length : 11

                Length : 8
            Values   : 
                Keys     : 
                    Length : 7

                    Length : 7

                    Length : 11

                    Length : 14

                    Length : 9

                    Length : 11
                Values   : 


                    IsPresent : True

                    value__ : 1

                    Length : 6

                    Length : 6

                    Length : 11
                SyncRoot : 
                    Release : 55448233
                    Verbose : True
                    ErrorAction : Stop
                    RepositoryName : Pester
                    OwnerName : Pester
                    AccessToken : PesterToken

                Count    : 6

                File          : C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
                Module        : Pester
                StartPosition : System.Management.Automation.PSToken
                Id            : 83a30dd9-ccba-4534-ba8a-55a99ad36b50
                Ast           : { $True }


            SyncRoot : 
                Comparer : System.OrdinalIgnoreCaseComparer
                Count    : 3
                Keys     : 
                    Length : 15

                    Length : 11

                    Length : 8
                Values   : 
                    Keys     : 
                        Length : 7

                        Length : 7

                        Length : 11

                        Length : 14

                        Length : 9

                        Length : 11
                    Values   : 


                        IsPresent : True

                        value__ : 1

                        Length : 6

                        Length : 6

                        Length : 11
                    SyncRoot : 
                        Release : 55448233
                        Verbose : True
                        ErrorAction : Stop
                        RepositoryName : Pester
                        OwnerName : Pester
                        AccessToken : PesterToken

                    Count    : 6

                    File          : C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
                    Module        : Pester
                    StartPosition : System.Management.Automation.PSToken
                    Id            : 83a30dd9-ccba-4534-ba8a-55a99ad36b50
                    Ast           : { $True }


                SyncRoot : 
                    Comparer : System.OrdinalIgnoreCaseComparer
                    Count    : 3
                    Keys     : 
                        Length : 15

                        Length : 11

                        Length : 8
                    Values   : 
                        Keys     : 
                            Length : 7

                            Length : 7

                            Length : 11

                            Length : 14

                            Length : 9

                            Length : 11
                        Values   : 


                            IsPresent : True

                            value__ : 1

                            Length : 6

                            Length : 6

                            Length : 11
                        SyncRoot : 
                            Release : 55448233
                            Verbose : True
                            ErrorAction : Stop
                            RepositoryName : Pester
                            OwnerName : Pester
                            AccessToken : PesterToken

                        Count    : 6

                        File          : C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
                        Module        : Pester
                        StartPosition : System.Management.Automation.PSToken
                        Id            : 83a30dd9-ccba-4534-ba8a-55a99ad36b50
                        Ast           : { $True }


                    SyncRoot : 
                        Comparer : System.OrdinalIgnoreCaseComparer
                        Count    : 3
                        Keys     : 
                            Length : 15

                            Length : 11

                            Length : 8
                        Values   : 
                            Keys     : 
                                Length : 7

                                Length : 7

                                Length : 11

                                Length : 14

                                Length : 9

                                Length : 11
                            Values   : 


                                IsPresent : True

                                value__ : 1

                                Length : 6

                                Length : 6

                                Length : 11
                            SyncRoot : 
                                Release : 55448233
                                Verbose : True
                                ErrorAction : Stop
                                RepositoryName : Pester
                                OwnerName : Pester
                                AccessToken : PesterToken

                            Count    : 6

                            File          : C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
                            Module        : Pester
                            StartPosition : System.Management.Automation.PSToken
                            Id            : 83a30dd9-ccba-4534-ba8a-55a99ad36b50
                            Ast           : { $True }


                        SyncRoot : 
                            Comparer : System.OrdinalIgnoreCaseComparer
                            Count    : 3
                            Keys     : 
                                Length : 15

                                Length : 11

                                Length : 8
                            Values   : 
                                Keys     : 
                                    Length : 7

                                    Length : 7

                                    Length : 11

                                    Length : 14

                                    Length : 9

                                    Length : 11
                                Values   : 


                                    IsPresent : True

                                    value__ : 1

                                    Length : 6

                                    Length : 6

                                    Length : 11
                                SyncRoot : 
                                    Release : 55448233
                                    Verbose : True
                                    ErrorAction : Stop
                                    RepositoryName : Pester
                                    OwnerName : Pester
                                    AccessToken : PesterToken

                                Count    : 6

                                File          : C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
                                Module        : Pester
                                StartPosition : System.Management.Automation.PSToken
                                Id            : 83a30dd9-ccba-4534-ba8a-55a99ad36b50
                                Ast           : { $True }


                            SyncRoot : 
                                Comparer : System.OrdinalIgnoreCaseComparer
                                Count    : 3
                                Keys     : 
                                    Length : 15

                                    Length : 11

                                    Length : 8
                                Values   : 
                                    Keys     : …
                                    Values   : …
                                    SyncRoot : 
                                        Release : 55448233
                                        Verbose : True
                                        ErrorAction : Stop
                                        RepositoryName : Pester
                                        OwnerName : Pester
                                        AccessToken : PesterToken

                                    Count    : 6

                                    File          : C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
                                    Module        : Pester
                                    StartPosition : System.Management.Automation.PSToken
                                    Id            : 83a30dd9-ccba-4534-ba8a-55a99ad36b50
                                    Ast           : { $True }


                                SyncRoot : 
                                    Comparer : System.OrdinalIgnoreCaseComparer
                                    Count    : 3
                                    Keys     : …
                                    Values   : …
                                    SyncRoot : …
        ScriptLineNumber : 9565
        OffsetInLine     : 13
        HistoryId        : 16
        ScriptName       : C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
        Line             : if (Test-ParameterFilter @params) {

        PositionMessage  : At C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1:9565 char:13
                           +         if (Test-ParameterFilter @params) {
                           +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        PSScriptRoot     : C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.1.1
        PSCommandPath    : C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
        InvocationName   : Test-ParameterFilter
        PipelineLength   : 1
        PipelinePosition : 1
        CommandOrigin    : Internal
    ErrorRecord       : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Cannot bind argument to parameter 'SessionState' because it is null.
            HResult : -2146233087
        CategoryInfo          : InvalidData: (:) [Test-ParameterFilter], ParentContainsErrorRecordException
        FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-ParameterFilter
        InvocationInfo        : 
            MyCommand        : Test-ParameterFilter
            ScriptLineNumber : 9565
            OffsetInLine     : 34
            HistoryId        : 16
            ScriptName       : C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
            Line             : if (Test-ParameterFilter @params) {

            PositionMessage  : At C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1:9565 char:34
                               +         if (Test-ParameterFilter @params) {
                               +                                  ~~~~~~~
            PSScriptRoot     : C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.1.1
            PSCommandPath    : C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
            CommandOrigin    : Internal
        ScriptStackTrace      : at Should-InvokeInternal, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 9565
                                at Should-Invoke, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 13118
                                at Invoke-Assertion, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 7357
                                at Should<End>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 7307
                                at <ScriptBlock>, C:\Users\JGrote\Projects\Press\Source\Public\Update-GithubRelease.Tests.ps1: line 33    
                                at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1924
                                at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1885
                                at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 2046
                                at Invoke-TestItem, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1142
                                at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 793
                                at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 848
                                at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1924
                                at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1885
                                at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 2049
                                at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 893
                                at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 848
                                at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1924
                                at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1885
                                at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 2049
                                at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 893
                                at Run-Test, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1601
                                at Invoke-Test, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 2387
                                at Invoke-Pester<End>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 4839
                                at <ScriptBlock>, <No file>: line 1
    TargetSite        : 
        Name          : CheckActionPreference
        DeclaringType : System.Management.Automation.ExceptionHandlingOps, System.Management.Automation, Version=7.2.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    StackTrace        : 
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at Should-InvokeInternal(Closure , FunctionContext )
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.CommandProcessorBase.Complete()
    Source            : System.Management.Automation
    HResult           : -2146233087
CategoryInfo          : InvalidData: (:) [Test-ParameterFilter], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Test-ParameterFilter
InvocationInfo        : 
    MyCommand        : Test-ParameterFilter
    ScriptLineNumber : 9565
    OffsetInLine     : 34
    HistoryId        : 16
    ScriptName       : C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
    Line             : if (Test-ParameterFilter @params) {

    PositionMessage  : At C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1:9565 char:34
                       +         if (Test-ParameterFilter @params) {
                       +                                  ~~~~~~~
    PSScriptRoot     : C:\Users\JGrote\OneDrive - Allied Digital Services LLC\Documents\PowerShell\Modules\Pester\5.1.1
    PSCommandPath    : C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1
    CommandOrigin    : Internal
ScriptStackTrace      : at Should-InvokeInternal, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 9565
                        at Should-Invoke, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 13118
                        at Invoke-Assertion, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 7357
                        at Should<End>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 7307
                        at <ScriptBlock>, C:\Users\JGrote\Projects\Press\Source\Public\Update-GithubRelease.Tests.ps1: line 33
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1924
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1885
                        at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 2046
                        at Invoke-TestItem, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1142
                        at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 793
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 848
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1924
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1885
                        at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 2049
                        at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 893
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 848
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services 
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1924
                        at <ScriptBlock>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1885
                        at Invoke-ScriptBlock, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 2049
                        at Invoke-Block, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 893
                        at Run-Test, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 1601
                        at Invoke-Test, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 2387
                        at Invoke-Pester<End>, C:\Users\JGrote\OneDrive - Allied Digital Services
LLC\Documents\PowerShell\Modules\Pester\5.1.1\Pester.psm1: line 4839
                        at <ScriptBlock>, <No file>: line 1
```

## Possible Solution? (optional)
The parameterfilter in this case is not specified, so not sure why it's having an issue in testing.

**Comment by JustinGrote** [comment]
For whatever reason the `$contextInfo.Hook` is missing
![image](https://user-images.githubusercontent.com/15258962/114205760-816e9800-990f-11eb-9daa-578a09f466c8.png)

**Comment by fflaten** [comment]
Thanks for the report. I believe this is same as #1878 👍

**Comment by JustinGrote** [comment]
@fflaten agreed, closing in favor.
