### ISSUE TITLE
Restore backwards compatibility to Pester V3

### ISSUE THREAD

**Issue by TobiasPSP** [pester/Pester#1952]
Pester V3 is still the default version shipping with Windows 10, and there are zillions of tests written in this version. Many of which are fairly simple. 

Still, when Pester is updated to version 5, they all fail. Since updating Pester is a user choice, a test author has no way of composing a test that will run in any client scenario. That's why many users have decided to actually ship the Pester version with their code that they use to test. Others give up. That's not good.

Tests show that a primary show stopper is the new design of "Should": the parameters now require a dash. The code uses dynamic parameters and regex to check the arguments of Should.

Instead of emitting a simple exception when hyphens are missing, this should trigger a *very simple* V3 compatibility mode which does just this:
- adds the dashes to the parameters automatically
- changes the test output format to the format used in V3 where each "It" result displays rather than just showing the "Describe" summary result.

The goal should be to re-enable the bulk of simple V3 tests to run in Pester V5 and restore the same look&feel. 

Please keep in mind that while it is trivial to adjust to the new syntax when writing new tests, there are zillions of existing tests that can't all be revisited just to add dashes.

**Comment by nohwnd** [comment]
I am open to discussing this. 

- There were some discussions and attempts to add the compatibility for Should already. When I tried it, it failed on Should -Invoke, but it was mostly and afterthought to do this few weeks before final release.

- The output would be hopefully as simple as setting the correct option, but question is when do you set it, we don't get to run the first test until after discovering all tests, and running at least the first one.

- The most problematic thing is not having setups in BeforeAll / BeforeEach, and we probably cannot detect and automatically migrate that either, as it would show false positives on code that generates tests. 
There should also be a way to distinguish Pester 3 and Pester 4 tests. Pester 4 tests are more likely to generate tests than Pester 3.

- Also PoweShell 2 compatibility was dropped. 

- And here is list of known breaking changes from v4, who knows what the list is from v3: https://pester.dev/docs/migrations/breaking-changes-in-v5

**Comment by nohwnd** [comment]
Also we need tests for this, but that should be easy, we have examples of both tests that check the result object, and tests that check the on screen output (both are in .ts.ps1, I think formatting tests run in different process, and all the other run in process)

**Comment by TobiasPSP** [comment]
IMHO Pester V3 compatibility is important because of the Win10 issue (it ships with V3). I am not too familiar with BeforeAll/BeforeEach as I have worked primarily with V3 so probably a good shot would be to look at a bunch of V3 tests and see how realistic it is to make them run again in V5. 

Regarding output mode, there must be some default value somewhere that is used when the user does not specify anything, so my thought was to change this default when V3 is detected. This would ensure that any user overrides via -Output or $PesterPreference would still work.

That said, I am just starting to look into this. Forgive me if I am naive. The important factor here should be to eval whether it is possible w/o a lot of overhead and code to add a reasonable backwards compatibility.

**Comment by TobiasPSP** [comment]
PS2 compatibility is not important. Win7 is off the grid. PS2 is unsafe to use.

**Comment by fflaten** [comment]
> Still, when Pester is updated to version 5, they all fail. Since updating Pester is a user choice, a test author has no way of composing a test that will run in any client scenario. That's why many users have decided to actually ship the Pester version with their code that they use to test. Others give up. That's not good.

That seems excessive when they can add `#Requires -Module @{ ModuleName = 'Pester'; MaximumVersion  = '3.99.99' }` at the top of the testfiles. 🙂  Pester v5 would fail that container, but still execute the rest:

```powershell
PS /workspaces/Pester> Invoke-Pester -Path ./Samples/demoRequirePester3.tests.ps1, ./Samples/demoRequirePester5.tests.ps1

Starting discovery in 2 files.
[-] Discovery in /workspaces/Pester/Samples/demoRequirePester3.tests.ps1 failed with:
System.Management.Automation.ScriptRequiresException: The script 'demoRequirePester3.tests.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: Pester.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
at <ScriptBlock>, /workspaces/Pester/bin/Pester.psm1: line 2957
at Invoke-File, /workspaces/Pester/bin/Pester.psm1: line 2966
at Invoke-BlockContainer, /workspaces/Pester/bin/Pester.psm1: line 2891
at Discover-Test, /workspaces/Pester/bin/Pester.psm1: line 1442
at Invoke-Test, /workspaces/Pester/bin/Pester.psm1: line 2403
at Invoke-Pester<End>, /workspaces/Pester/bin/Pester.psm1: line 5090
at <ScriptBlock>, <No file>: line 1
Discovery finished in 22ms.
Running tests.
[+] /workspaces/Pester/Samples/demoRequirePester5.tests.ps1 56ms (4ms|41ms)
Tests completed in 68ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
Container failed: 1
  - /workspaces/Pester/Samples/demoRequirePester3.tests.ps1
```

Expecting full compatibility two major versions later is optimistic. Multiple breaking changes outside of the new should-syntax (released in Pester v4?). Ex. Pester v5 no longer supports `$MyInvocation.MyCommand.Path` or this code at the top of the file in general (due to Discovery-phase).
```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"
```

If implemented, there should at least be a clear warning when invoked that it's running is limited compatiblity mode. Changing the output to v3-style as well could give false hope that everything would work when the shim would only fix 2 of 10 breaking changes.

**Comment by nohwnd** [comment]
Revisiting this after a few years. The main driver here was that Windows 10 shipped Pester v3 — but Win10 is now EOL, and v3/v4 are long past support, so that justification is gone. And as discussed at the time, a real compat shim can't cover the breaking changes that matter most (BeforeAll/BeforeEach placement, Discovery-phase behavior, reliable v3-vs-v4 detection); auto-adding dashes to Should and flipping the output style would only paper over a fraction of it while giving false confidence. Given five years without traction and the original motivation gone, I'm closing this as won't-do. The right path remains pinning the Pester version for legacy tests (import-module -MaximumVersion) rather than a compatibility mode. Thanks @TobiasPSP for the thoughtful writeup.
