### ISSUE TITLE
Mock of Invoke-WebRequest not being depending on parameter value used

### ISSUE THREAD

**Issue by robhalevt** [pester/Pester#2142]
## General summary of the issue
I've got a function defined in a module that calls `Invoke-WebRequest`. Our test mocks `Invoke-WebRequest` to have consistent results. We found that when the `Url` parameter is `'http://'` or `'https://'` the actual implementation of `Invoke-WebRequest` appears to be called because a `UriFormatException` is thrown. Providing other values to that parameter result in the mock being used.

## Describe your environment
Pester version     : 5.3.1 C:\Users\\[myUserName]\\[myEmployerOneDriveName]\Documents\PowerShell\Modules\Pester\5.3.1\Pester.psm1
PowerShell version : 7.2.1
OS version         : Microsoft Windows NT 10.0.19044.0

## Steps to reproduce

**CallGetWebRequest.psm1**
```powershell
function Get-MyWebStuff {
  param(
    [String] $Url
  )

  try {
    Write-Host "";
    Write-Host "Invoking web request for $Url";
    $response = Invoke-WebRequest -Uri $Url -Method Get;

    # Print status and body of response
    $status = $response.StatusCode
    $body = $response.Content

    Write-Host "Status Code: $status"
    Write-Host "Response Length: $($body.Length)"
  }
  catch {
    Write-Error $_.Exception.Message
  }
}

Export-ModuleMember Get-MyWebStuff
```

**CallGetWebRequest.Tests.ps1**
```powershell
BeforeAll {
  $modulePath = $PSScriptRoot;
  Remove-Module CallGetWebRequest -ErrorAction SilentlyContinue;
  Import-Module (Join-Path $modulePath 'CallGetWebRequest.psm1') -Force;

  Mock -ModuleName CallGetWebRequest Invoke-WebRequest { @{ StatusCode = 200; Content = "foo" } };
  Mock -ModuleName CallGetWebRequest Write-Host;
  Mock -ModuleName CallGetWebRequest Write-Error;
}

Describe "Invoke-WebRequest mock issue" {
  It "Uses the mock when URL is something like '<url>'" -ForEach @(
    @{ Url = 'https://covidstandardtime.com/'}
    @{ Url = '?value=fooBar'}
    @{ Url = 'razzle-dazzle'}
  ) {
    Get-MyWebStuff -Url $url;
    Should -Invoke Write-Host -ModuleName CallGetWebRequest -Times 1 -ParameterFilter { $Object -eq "Status Code: 200" }
  }

  Context "Only protocol is given to URL" {
    It "Shouldn't throw an exception for '<url>'" -ForEach @(
      @{ Url = 'http://'}
      @{ Url = 'https://'}
    ) {
      Get-MyWebStuff -Url $url;
      Should -Not -Invoke Write-Error -ModuleName CallGetWebRequest
    }
  }
}
```

## Expected Behavior
The mock implementation to be used regardless of the value provided to a parameter

## Current Behavior
Certain values provided to the mock result in the actual implementation to be run (apparently)

```powershell
❯ Invoke-Pester -Output Detailed
Pester v5.3.1

Starting discovery in 1 files.
Discovery found 5 tests in 48ms.
Running tests.

Running tests from 'C:\Research\PesterIssueWithMock\CallGetWebRequest.Tests.ps1'
Describing Invoke-WebRequest mock issue
  [+] Uses the mock when URL is something like 'https://covidstandardtime.com/' 23ms (21ms|2ms)
  [+] Uses the mock when URL is something like '?value=fooBar' 17ms (16ms|1ms)
  [+] Uses the mock when URL is something like 'razzle-dazzle' 25ms (23ms|2ms)
 Context Only protocol is given to URL
   [-] Shouldn't throw an exception for 'http://' 18ms (15ms|2ms)
    at Should -Not -Invoke Write-Error -ModuleName CallGetWebRequest, C:\Research\PesterIssueWithMock\CallGetWebRequest.Tests.ps1:27
    at <ScriptBlock>, C:\Research\PesterIssueWithMock\CallGetWebRequest.Tests.ps1:27
    Expected Write-Error in module CallGetWebRequest not to be called exactly 1 times
   [-] Shouldn't throw an exception for 'https://' 24ms (23ms|1ms)
    at Should -Not -Invoke Write-Error -ModuleName CallGetWebRequest, C:\Research\PesterIssueWithMock\CallGetWebRequest.Tests.ps1:27
    at <ScriptBlock>, C:\Research\PesterIssueWithMock\CallGetWebRequest.Tests.ps1:27
    Expected Write-Error in module CallGetWebRequest not to be called exactly 1 times
Tests completed in 293ms
Tests Passed: 3, Failed: 2, Skipped: 0 NotRun: 0
```

**Comment by nohwnd** [comment]
It is working correctly. You are providing string that is not a correct URI to a parameter that has type `Uri`. It cannot parse it and throws. 

```powershell
[uri]"https://"

InvalidArgument: Cannot convert value "https://" to type "System.Uri". 
Error: "Invalid URI: The hostname could not be parsed."
```

Pester mocks inspect the parameters of the mocked command and replicate it to give you additional safety, you can remove the parameter type using ` -RemoveParameterType Uri`, and optionally also remove parameter validation using `-RemoveParameterValidation Uri`, but it is not needed in your case.

**Comment by robhalevt** [comment]
@nohwnd can you help me understand why other parameter values in the tests I provided are resulting in the mock running if the parameter is being inspected? For example, `razzle-dazzle`. If I use that value in PowerShell to instantiate a `System.Uri` (like this):
```powershell
$url = New-Object -TypeName System.Uri -ArgumentList "razzle-dazzle"
```
it throws a `System.UriFormatException`. Here's the results of `Get-Error` (meanwhile Pester runs the mock)
```
Exception             :
    Type           : System.Management.Automation.MethodInvocationException
    ErrorRecord    :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Exception calling ".ctor" with "1" argument(s): "Invalid URI: The format of the URI could not be
determined."
            HResult : -2146233087
        CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : DotNetconstructorTargetInvocation
    TargetSite     :
        Name          : AuxiliaryConstructorInvoke
        DeclaringType : System.Management.Automation.DotNetAdapter, System.Management.Automation, Version=7.2.2.500,
Culture=neutral, PublicKeyToken=31bf3856ad364e35
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Message        : Exception calling ".ctor" with "1" argument(s): "Invalid URI: The format of the URI could not be
determined."
    InnerException :
        Type       : System.UriFormatException
        TargetSite :
            Name          : CreateThis
            DeclaringType : uri
            MemberType    : Method
            Module        : System.Private.Uri.dll
        Message    : Invalid URI: The format of the URI could not be determined.
        Source     : System.Private.Uri
        HResult    : -2146233033
        StackTrace :
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
    Source         : System.Management.Automation
    HResult        : -2146233087
    StackTrace     :
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation,
Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.InvokeResolvedConstructor(MethodInformation bestMethod, Object[]
newArguments, Object[] arguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors,
Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors,
Object[] args)
CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
InvocationInfo        :
    MyCommand        : New-Object
    ScriptLineNumber : 1
    OffsetInLine     : 8
    HistoryId        : 1
    Line             : $url = New-Object -TypeName System.Uri -ArgumentList "razzle-dazzle"
    PositionMessage  : At line:1 char:8
                       + $url = New-Object -TypeName System.Uri -ArgumentList "razzle-dazzle"
                       +        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : New-Object
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

I'm just trying to understand. Thank you!

**Comment by nohwnd** [comment]
Sure, it is because the way you construct it is not how it happens when the parameter is populated. This conversion works, so the parameter gets it's value: 

```powershell
[uri]"razzle-dazzle"
```

**Comment by nohwnd** [comment]
Rules how the conversions are applied are here: 
https://docs.microsoft.com/en-us/powershell/scripting/lang-spec/chapter-06?view=powershell-7.2#618-net-conversion

The built in tracing shows exactly how the conversion is done: 

```
 Trace-Command -Expression { function f ([uri]$Address) {}; f "razzle" } -Name TypeConversion -PSHost -Option All

# output
DEBUG: 2022-04-22 22:03:15.1363 TypeConversion Information: 0 :                 Converting "razzle" to "System.Uri".

```
That does not have much info because it just works, but try it with a hashtable for example, and see how much it tries before failing:

``` 
Trace-Command -Expression { function f ([uri]$Address) {}; f @{ "razzle" = "n" } } -Name TypeConversion -PSHost -Option All
DEBUG: 2022-04-22 22:04:18.2365 TypeConversion Information: 0 :                 Converting "System.Collections.Hashtable" to "System.Uri".
DEBUG: 2022-04-22 22:04:18.2367 TypeConversion Information: 0 :                     Type Conversion failed.
DEBUG: 2022-04-22 22:04:18.2499 TypeConversion Information: 0 :                 Converting ref to boolean.
DEBUG: 2022-04-22 22:04:18.2502 TypeConversion Information: 0 :                 Converting "DetailedView" to "System.Management.Automation.ErrorView".
DEBUG: 2022-04-22 22:04:18.2503 TypeConversion Information: 0 :                     Calling case sensitive Enum.Parse
DEBUG: 2022-04-22 22:04:18.2504 TypeConversion Information: 0 :                 Converting "ConciseView" to "System.Management.Automation.ErrorView".
DEBUG: 2022-04-22 22:04:18.2505 TypeConversion Information: 0 :                     Calling case sensitive Enum.Parse
DEBUG: 2022-04-22 22:04:18.2525 TypeConversion Information: 0 :                 Converting null to "".
DEBUG: 2022-04-22 22:04:18.2531 TypeConversion Information: 0 :                 Converting null to "".
DEBUG: 2022-04-22 22:04:18.2533 TypeConversion Information: 0 :                 Converting null to "".
DEBUG: 2022-04-22 22:04:18.2534 TypeConversion Information: 0 :                 Converting ref to boolean.
DEBUG: 2022-04-22 22:04:18.2535 TypeConversion Information: 0 :                 Converting string to boolean.
DEBUG: 2022-04-22 22:04:18.2536 TypeConversion Information: 0 :                 Converting "ParserError" to "System.Management.Automation.ErrorCategory".
DEBUG: 2022-04-22 22:04:18.2537 TypeConversion Information: 0 :                     Calling case sensitive Enum.Parse
DEBUG: 2022-04-22 22:04:18.2538 TypeConversion Information: 0 :                 Converting null to boolean.
DEBUG: 2022-04-22 22:04:18.2539 TypeConversion Information: 0 :                 Converting "ParserError" to "System.Management.Automation.ErrorCategory".
DEBUG: 2022-04-22 22:04:18.2540 TypeConversion Information: 0 :                     Calling case sensitive Enum.Parse
DEBUG: 2022-04-22 22:04:18.2541 TypeConversion Information: 0 :                 Converting ref to boolean.
DEBUG: 2022-04-22 22:04:18.2542 TypeConversion Information: 0 :                 Converting ref to boolean.
DEBUG: 2022-04-22 22:04:18.2543 TypeConversion Information: 0 :                 Converting string to boolean.
DEBUG: 2022-04-22 22:04:18.2544 TypeConversion Information: 0 :                 Converting "ParserError" to "System.Management.Automation.ErrorCategory".
DEBUG: 2022-04-22 22:04:18.2544 TypeConversion Information: 0 :                     Calling case sensitive Enum.Parse
DEBUG: 2022-04-22 22:04:18.2546 TypeConversion Information: 0 :                 Converting ref to boolean.
DEBUG: 2022-04-22 22:04:18.2546 TypeConversion Information: 0 :                 Converting ref to boolean.
DEBUG: 2022-04-22 22:04:18.2547 TypeConversion Information: 0 :                 Converting string to boolean.
DEBUG: 2022-04-22 22:04:18.2548 TypeConversion Information: 0 :                 Converting "f" to "System.String".
DEBUG: 2022-04-22 22:04:18.2549 TypeConversion Information: 0 :                     Converting object to string.
DEBUG: 2022-04-22 22:04:18.2550 TypeConversion Information: 0 :                 Converting "Ignore" to "System.Management.Automation.ActionPreference".
DEBUG: 2022-04-22 22:04:18.2551 TypeConversion Information: 0 :                     Calling case sensitive Enum.Parse
DEBUG: 2022-04-22 22:04:18.2553 TypeConversion Information: 0 :                 Converting ref to boolean.
DEBUG: 2022-04-22 22:04:18.2555 TypeConversion Information: 0 :                 Converting null to boolean.
DEBUG: 2022-04-22 22:04:18.2556 TypeConversion Information: 0 :                 Converting "ConciseView" to "System.Management.Automation.ErrorView".
DEBUG: 2022-04-22 22:04:18.2556 TypeConversion Information: 0 :                     Calling case sensitive Enum.Parse
f: Cannot process argument transformation on parameter 'Address'. Cannot convert the "System.Collections.Hashtable" value of type "System.Collections.Hashtable" to type "System.Uri".
```
