### ISSUE TITLE
Pester container data dictionary object gets populated with test parameters after invoke-pester

### ISSUE THREAD

**Issue by GitHubEddie** [pester/Pester#2357]
### Checklist

- [X] Issue has a meaningful title
- [X] I have searched the existing issues. See [all issues](https://github.com/pester/Pester/issues?q=is%3Aissue)
- [X] I have tested using the latest version of Pester. See [Installation and update guide](https://pester.dev/docs/introduction/installation).

### What is the issue?

Using New-PesterContainer I am creating a container that has the Data dictionary set with parameter values.  
```
PS C:\sandpit> $paramcontainer = New-PesterContainer -Path '.\Test-PesterContainerParams.Tests.ps1' -Data @{ Param2 = 'Should be this parameter only'  }

PS C:\sandpit> $paramcontainer.data

Name                           Value
----                           -----
Param2                         Should be this parameter only

```

The test script that takes these parameters has mandatory parameter sets that will work when only one of those variables is set.
```
param(
    [Parameter(Mandatory = $true,ParameterSetName = 'ParamSet1')]
    $Param1,
    [Parameter(Mandatory = $true,ParameterSetName = 'ParamSet2')]
    $Param2
```

First run of the test script using Invoke-Pester with the container works as expected.
```
PS C:\sandpit> invoke-pester -container $paramcontainer -Output Detailed
```

However, the first run populates the container Data dictionary with every parameter the test script has.  
```
PS C:\sandpit> $paramcontainer.data
 
Name                           Value
----                           -----
Param2                         Should be this parameter only
Param1                         BeforeDiscovery Block
```

This breaks subsequent executions of the same container.  

### Expected Behavior

I was expecting the container Data dictionary to only populate once when New-PesterContainer is executed.  Not when the test script executes with Invoke-Pester.

### Steps To Reproduce

Example test script with results.  First run is successful, second run fails.
```
# Test-PesterContainerParams.Tests.ps1
param(
    [Parameter(Mandatory = $true,ParameterSetName = 'ParamSet1')]
    $Param1,
    [Parameter(Mandatory = $true,ParameterSetName = 'ParamSet2')]
    $Param2,
    $Param3 = 'Default value',
    $Param4 = 'Default value',
    $Param5
)

BeforeDiscovery {
    $Param1 = 'BeforeDiscovery Block'
    $Param2 = 'BeforeDiscovery Block'
    $Param4 = 'BeforeDiscovery Block'
    $Var6 = 'BeforeDiscovery Block'
}

BeforeAll {
    $Param1 = 'BeforeAll Block'
    $Param2 = 'BeforeAll Block'
}
 

Describe 'Describe block' {
    Context 'Context block' {
        It 'It block' {
            $Param1 = 'It Block'
            $Param2 = 'It Block'
            1 | Should -Be 1
        }
    }
}
```

Populate pester container, Data dictionary is correct.
```
PS C:\sandpit> $paramcontainer = New-PesterContainer -Path '.\Test-PesterContainerParams.Tests.ps1' -Data @{ Param2 = 'Should be this parameter only'  }

PS C:\sandpit> $paramcontainer.data

Name                           Value
----                           -----
Param2                         Should be this parameter only
```

First run of test is successful
```
PS C:\sandpit> invoke-pester -container $paramcontainer -Output Detailed

Pester v5.4.1
 
Starting discovery in 1 files.
Discovery found 1 tests in 244ms.
Running tests.
Running tests from 'C:\sandpit\Test-PesterContainerParams.Tests.ps1'
Describing Describe block
Context Context block
   [+] It block 13ms (7ms|6ms)
Tests completed in 584ms
Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 0
```

**ISSUE:** First run has updated Data dictionary object in container
```
PS C:\sandpit> $paramcontainer.data
 
Name                           Value
----                           -----
Param5
Param4                         BeforeDiscovery Block
Param2                         Should be this parameter only
Param1                         BeforeDiscovery Block
Param3                         Default value
```

Second attempt to run test with the same container fails
```
PS C:\sandpit> invoke-pester -container $paramcontainer -Output Detailed
Pester v5.4.1

Starting discovery in 1 files.
[-] Discovery in C:\sandpit\Test-PesterContainerParams.Tests.ps1 failed with:
System.Management.Automation.ParameterBindingException: Parameter set cannot be resolved using the specified named parameters.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
at <ScriptBlock>, C:\Modules\pester\Pester.psm1: line 3003
at Invoke-File, C:\Modules\pester\Pester.psm1: line 3012
at Invoke-BlockContainer, C:\Modules\pester\Pester.psm1: line 2918
at Discover-Test, C:\Modules\pester\Pester.psm1: line 1454
at Invoke-Test, C:\Modules\pester\Pester.psm1: line 2438
at Invoke-Pester<End>, C:\Modules\pester\Pester.psm1: line 5284
at <ScriptBlock>, <No file>: line 1
Discovery found 0 tests in 163ms.
Running tests.
Tests completed in 160ms
Tests Passed: 0, Failed: 0, Skipped: 0 NotRun: 0
Container failed: 1
  - C:\sandpit\Test-PesterContainerParams.Tests.ps1
```

### Describe your environment

```
Pester version     : 5.4.1 C:\Users\A.User\AppData\Roaming\WindowsPowerShell\Modules\pester\Pester.psm1
PowerShell version : 5.1.19041.2673
OS version         : Microsoft Windows NT 10.0.19044.0
```

### Possible Solution?

Could it be a cloning issue with the Data dictionary hashtable?

**Comment by nohwnd** [comment]
Yup, can repro on the latest version as well, I suspect the same thing as you do. I saw some fixes around cloning, but maybe we are not cloning early enough.

**Comment by fflaten** [comment]
> Yup, can repro on the latest version as well, I suspect the same thing as you do. I saw some fixes around cloning, but maybe we are not cloning early enough.

Yeah, it's an oversight. We clone the data when creating the container-object. In this scenario that is done in `New-PesterContainer`, which means the returned container has the cloned data-reference.

**Comment by fflaten** [comment]
It also highlight a few other issues with `Add-MissingContainerParameters` caused by me being naive.

1. Default values for script parameters in a different parameter set will be added to the Data. I assumed that was too complex to be seen in the wild.
2. Overriding parameters in `BeforeDiscovery` are picked up in Data because we look up the missing parameter values later.
