### ISSUE TITLE
The System.Xml.Schema.XmlSchema]::Read() method does not like the TestDrive provider

### ISSUE THREAD

**Issue by adbertram** [pester/Pester#638]
I'm trying to write a temporary XML schema (XSD) file to TestDrive. Once created, I then run a function that contains the following code:

```
describe 'foo' {

    $schemaFilePath = TestDrive:\schema.xsd

    $validSchema = @'
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
        <xs:include schemaLocation="../Identities/Identities.xsd"/>
</xs:schema>
'@

    Add-Content -Path TestDrive:\schema.xsd -Value $validSchema -Encoding UTF8
    it 'does not throw an exception' {
        $schemaReader = New-Object System.Xml.XmlTextReader TestDrive:\schema.xsd
	[System.Xml.Schema.XmlSchema]::Read($schemaReader, { Write-Error $args[1].Exception })	
    }
}
```

The code above will always throw an exception with the message:

```
      Exception             : System.Management.Automation.MethodInvocationException: Exception calling "Read" with "2" argument(s): "The URI prefix is not re
cognized." ---> System.NotSupportedException: The URI prefix is not recognized.
                                 at System.Net.WebRequest.Create(Uri requestUri, Boolean useUriBase)
                                 at System.Xml.XmlDownloadManager.GetNonFileStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cach
ePolicy)
                                 at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
                                 at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
                                 at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Obj
ect userData)
                                 at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
                                 at System.Xml.XmlTextReaderImpl.OpenUrl()
                                 at System.Xml.XmlTextReaderImpl.Read()
                                 at System.Xml.Schema.Parser.StartParsing(XmlReader reader, String targetNamespace)
                                 at System.Xml.Schema.Parser.Parse(XmlReader reader, String targetNamespace)
                                 at System.Xml.Schema.XmlSchema.Read(XmlReader reader, ValidationEventHandler validationEventHandler)
                                 at CallSite.Target(Closure , CallSite , Type , Object , ScriptBlock )
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

When I run this code inside of the test yet write it to the local filesystem, it works fine. Something is happening to the XSD on the TestDrive that the XML object does not like.

**Comment by johlju** [comment]
The TestDrive:\  does not exist until you are inside the Describe-block. 
So move Add-Content inside the Describe-block and I think it will work. 
https://github.com/pester/Pester/wiki/TestDrive

**Comment by adbertram** [comment]
@johlju I apologize. My example was not clear. I am building the file inside of the describe block and verified it's contents with Get-Content inside of the test. The file is there but is not formatted correctly somehow.

**Comment by dlwyatt** [comment]
The .Net framework doesn't know how to work with PSDrives. You'll have to give it a valid file system path, such as $TestDrive\etc

**Comment by adbertram** [comment]
Thanks. Does this Wiki section explain it well?

https://github.com/pester/Pester/wiki/TestDrive

**Comment by nohwnd** [comment]
Not really. TestDrive is just a folder in somewhere in temp. For conevience we add it as a PsDrive TestDrive:\. But you can still laverage it with .NET code to avoid cleaning up manually. You just need to use its actual path, instead of the PSDrive. That path is stored in $TestDrive variable, as Dave pointed out.

**Comment by adbertram** [comment]
Thanks. I didn't realize that $TestDrive was an actual path. Duh. Anyway, I
got the Wiki page updated.
